config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :notifications, only: :index
  resources :chats, only: [:create]

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
   
  end
  resources :groups do
      get "join" => "groups#join"
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
      delete "all_destroy" => 'groups#all_destroy'
  end


  devise_scope :user do
    post 'users/guest_sign_in' , to: 'users/sessions#guest_sign_in'

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord

  default_scope -> { order(created_at: :desc) }
  belongs_to :chat, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.all
    @notifications.where(checked: false).each do |notification|
      notification.update_attribute(:checked, true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false) if current_user
  end
end

app/views/notifications/_notification.html.erb
<div class='m-2'>
  <%= link_to user_path(notification.visitor) do %>
    <%= notification.visitor.name %>
  <% end %>
  <span>さんが</span>

  <% if notification.action == 'chat' %>
    <%= link_to 'あなたにメッセージ', chat_path(notification.visitor), style:"font-weight: bold;", class: "border-bottom" %>
    <%= "を送りました" %>
  <% end %>
  <span><%= " (#{time_ago_in_words(notification.created_at)}前)" %></span><br>
</div>

app/views/notifications/index.html.erb
<div class="text-center">
  <% notifications = @notifications.where.not(visitor_id: current_user.id) %>
  <!--自分の投稿に対するいいね、コメントは通知に表示しない-->

  <% if notifications.exists? %>
    <%= render notifications %>

  <% else %>
   <p>通知はありません</p>
  <% end %>
</div>