config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :notifications, only: :index
  resources :chats, only: [:create]

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
   
  end
  resources :groups do
      get "join" => "groups#join"
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
      delete "all_destroy" => 'groups#all_destroy'
  end


  devise_scope :user do
    post 'users/guest_sign_in' , to: 'users/sessions#guest_sign_in'

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships, class_name: "Relationship",foreign_key: :follower_id ,dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :followed_id  ,dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :group_users 
  has_many:groups, through: :group_users,dependent: :destroy
  has_many :owned_groups, class_name: "Group"
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def self.looks(search, word)
    if search  ==  "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end


  def follow(user_id)
    relationships.create!(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
   followings.include?(user)
  end





  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {  maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
    user.password = SecureRandom.urlsafe_base64
    user.name = "guestuser"
    end
  end

  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
        @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
     @user = User.find(params[:id])
  if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
  else

      render "edit"
  end
  end


  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end

  end
  
  

  private

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません'

    end
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end


end

app/helpers/users_helper.rb
module UsersHelper
  
  def current_user?(user)
     user == current_user
  end
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>

        <td><%= user.name %></td>
        <td>フォロー数:</td>

      	<td> <%= user.followings.count %>	</td>
      	 
        <td>フォロワー数:</td>
	      <td><%= user.followers.count %></td>
        <% unless current_user?(user) %>
        <% if current_user.following?(user) %>
         <td><%= link_to "フォローを外す" ,user_relationships_path(user.id), method: :delete %></td>
        <% else %>
         <td><%= link_to "フォローする" ,user_relationships_path(user.id), method: :post %></td>
        <% end %>
        <% end %>
        <td><%= link_to 'Show', user %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
	</tr>
	<tr>
	  <th>follows</th>
	  <th><%= link_to relationships_followings_path(user_id: user.id)  do %>
	    <%= user.followings.count %>
	    <% end %>
	  </th>
	  
	</tr>
	<tr>
	   <th>followers</th>
	   <th><%= link_to relationships_followers_path(user_id: user.id) do %>
	    <%= user.followers.count %><% end %>
	   </th>
	</tr>

</table>
 <% unless current_user?(user) %>
   <% if current_user.following?(user) %>
     <%= link_to "フォローを外す" ,user_relationships_path(user.id), method: :delete , class: "btn btn-info" %>
   <% else %>
    <%= link_to "フォローする" ,user_relationships_path(user.id), method: :post ,  class:'btn btn-success' %>
   <% end %>
 <% end %>


<div class='row'>
	<% if user.name != "guestuser" %>
  <% if @user == current_user %>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
  <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', user: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render '/books/form', book: @book %>
    </div>
   <div class='col-md-8 offset-md-1'>
     <h2>Users</h2>
     <%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %>
     <%= render 'index',users: @users %>
   </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <%= render 'chats/chat', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      　<h2>Books</h2>
        <%= render 'books/index',books: @books %>
        <h2>投稿数の前日比・前週比</h2>
        <table class="table">
          <thead>
            <tr>
              <th>今日の投稿</th>
              <th>昨日の投稿</th>
              <th>前日比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @today_book.count %></td>
              <td><%= @yesterday_book.count %></td>
              <% if @yesterday_book.count == 0 %>
                <td>前日の投稿はなし</td>
              <% else %>
                <td><% @the_day_before =   @today_book.count / @yesterday_book.count.to_f  %>
                <%= (@the_day_before * 100).round %>%</td>
              <% end %>
            </tr>
          </tbody>
        </table>

         <table class="table">
          <thead>
            <tr>
               <th>今週の投稿</th>
               <th>先週の投稿</th>
               <th>前週比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
               <td><%= @this_week_book.count %></td>
               <td><%= @last_week_book.count %></td>
             <% if @last_week_book.count == 0 %>
                <td>先週の投稿はなし</td>
             <% else %>
              　<td><% @the_week_before =   @this_week_book.count / @last_week_book.count.to_f  %>
       　     <%= (@the_week_before * 100).round %>%</td>
             <% end %>
            </tr>
          </tbody>
        </table>
         <table class="table">
   <thead>
    <tr>
     <th>６日前</th>
     <th>5日前</th>
     <th>4日前</th>
     <th>3日前</th>
     <th>２日前</th>
     <th>昨日</th>
     <th>今日</th>
    </tr>
   </thead>
   <tbody>
    <tr>
     <th><%= @books.created_6days.count %></th>
     <th><%= @books.created_5days.count %></th>
     <th><%= @books.created_4days.count %></th>
     <th><%= @books.created_3days.count %></th>
     <th><%= @books.created_2days.count %></th>
     <th><%= @yesterday_book.count %></th>
     <th><%= @today_book.count %></th>
    </tr>
   </tbody>
  </table>
  <canvas id="myChart" width="300" height="100"> </canvas>

    <script> 
    var ctx = document.getElementById("myChart").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',                      
        data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
            datasets: [{
                label: "投稿数",
                data: [<%= @books.created_6days.count %>, <%= @books.created_5days.count %>, <%= @books.created_4days.count %>, <%= @books.created_3days.count %>, <%= @books.created_2days.count %>, <%= @yesterday_book.count %>, <%= @today_book.count%>],
                backgroundColor: 'rgba(255, 80, 120, 1.0)',
                borderColor: 'rgba(255, 80, 120, 1.0)',
                fill: false
            }]
        },
    });
</script>
    </div>
  </div>
</div>